### ISSUE TITLE
Subtitle as element of titleType

### ISSUE THREAD

**Issue by bingert** [AV-EFI/av-efi-schema#15]
Should we add "Subtitle" to the list of controlled vocabulary [work_1.1_titleType.json](https://github.com/AV-EFI/av-efi-schema/blob/main/Controlled_Vocabularies/work_1.1_titleType.json)

**Comment by EOltmanns** [comment]
There has been consensus in Metadatenfachgruppe that "Subtitle" should
not be added to the titleTypes.

Reasoning: title is a repeatable attribute and if one of them is
declared subtitle it would be unclear would "main title" it is meant
to be added to. Also, it appears to be very rarely used in local
databases anyway, probably for similar reasons.

**Comment by EOltmanns** [comment]
Subtitle has been removed as agreed.
